### ISSUE TITLE
No CI report in PRs anymore

### ISSUE THREAD

**Issue by marcelstoer** [nodemcu/nodemcu-firmware#3085]
We see all the CI builds at https://travis-ci.org/github/nodemcu/nodemcu-firmware/pull_requests (i.e. they do run) but GitHub doesn't show the results anymore in the respective PR view.

**Comment by marcelstoer** [comment]
This has been resolved. In #3132 by @vsky279 GitHub notifies us again that the build failed.

**Comment by vsky279** [comment]
Funny thing is that I did not resolve anything in #3132, It just started working.
